export type IpcHandlerChannel =
    | 'window/minimize'
    | 'window/maximize'
    | 'window/close'
    | 'game/list'
    | 'game/verify'
    | 'game/setup'
    | 'game/profiles'
    | 'game/loaders'
    | 'game/profiles/create'
    | 'game/profiles/get'
    | 'game/profiles/start'
    | 'game/profiles/mods/install'
    | 'game/profiles/mods/uninstall'
    | 'game/profiles/mods/install/list'
    | 'mods/search'
    | 'mods/get'
    | 'mods/comments'
    | 'app/titlebar'

export type IpcListenerChannel = 'game/profiles/mods/install'
